FROM debian:bookworm

WORKDIR /workspace/pulse

RUN apt-get update && apt-get install -qq \
        dpkg-dev \
        debhelper \
        dh-python \
        python3-all \
        pybuild-plugin-pyproject \
        python3-poetry-core \
        python3-pymodbus \
        python3-influxdb

CMD dpkg-buildpackage -b -rfakeroot -us -uc
